user = input("Please enter your game user name ")

score = 0

print("What would you like to play, General Riddles, Academic Riddles, or Romantic Riddles?")
answer = input("? ")

if answer == "General":
    print("Welcome to the General Riddles ", user)

    

if answer == "Academic":
    print("Welcome to the Academic Riddles ", user)

if answer == "Romantic":
    print("Welcome to the Romantic Riddles ", user)

print("wich level do you prefer ")
answer = input("? ")
